const applications = [
  {
    id: 1,
    dateApplied: "2020-06-15",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Instacart",
    position: "Staff Full-Stack Software Engineer, Admin Tools",
    status: "Failed",
    comment: "",
  },
  {
    id: 2,
    dateApplied: "2020-06-16",
    location: { country: "Canada", state: "ON", city: "Mississuaga" },
    company: "Intuit",
    position: "Staff Software Developer",
    status: "Applied",
    comment: "",
  },
  {
    id: 3,
    dateApplied: "2020-06-24",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Uber",
    position: "Sr. Software Engineer - Backend",
    status: "Failed",
    comment: "",
  },
  {
    id: 4,
    dateApplied: "2020-06-26",
    location: { country: "Canada", state: "ON", city: "Markham" },
    company: "Partech",
    position: "Senior Software Engineer",
    status: "Failed",
    comment: "",
  },
  {
    id: 5,
    dateApplied: "2020-06-26",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "HomeStars",
    position: "Software Engineer",
    status: "Applied",
    comment: "",
  },
  {
    id: 6,
    dateApplied: "2020-06-26",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Proofpoint",
    position: "Senior Software Engineer",
    status: "Failed",
    comment: "",
  },
  {
    id: 7,
    dateApplied: "2020-06-27",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Altis Technology Recruitment",
    position: "Senior Full Stack Developer",
    status: "Applied",
    comment: "",
  },
  {
    id: 8,
    dateApplied: "2020-06-27",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Nextdoor",
    position: "Software Engineer - Local Businesses",
    status: "Failed",
    comment: "",
  },
  {
    id: 9,
    dateApplied: "2020-06-27",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Proofpoint",
    position: "Principal Software Engineer",
    status: "Applied",
    comment: "",
  },
  {
    id: 10,
    dateApplied: "2020-06-27",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Thirty Madison",
    position: "Software Engineer - Full Stack (Canada)",
    status: "Failed",
    comment: "",
  },
  {
    id: 11,
    dateApplied: "2020-06-27",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Fi.span",
    position: "Intermediate C# Software Developer - ERP Team",
    status: "Failed",
    comment: "",
  },
  {
    id: 12,
    dateApplied: "2020-06-27",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "ClearVision Technologies, Inc.",
    position: "Software Engineer",
    status: "Applied",
    comment: "",
  },
  {
    id: 13,
    dateApplied: "2020-06-27",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Capital One",
    position: "Senior Front End Developer",
    status: "Applied",
    comment: "",
  },
  {
    id: 14,
    dateApplied: "2020-06-29",
    location: { country: "Canada", state: "ON", city: "Markham" },
    company: "Allstate Canada",
    position: "Senior Software Engineer",
    status: "Applied",
    comment: "",
  },
  {
    id: 15,
    dateApplied: "2020-06-29",
    location: { country: "Canada", state: "ON", city: "Markham" },
    company: "Allstate Canada",
    position: "Full Stack Software Engineer",
    status: "Applied",
    comment: "",
  },
  {
    id: 16,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Danavation",
    position: "Full Stack Developer (.NET)",
    status: "Applied",
    comment: "",
  },
  {
    id: 17,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "ON", city: "Toronto" },
    company: "Clutch",
    position: "Software Engineer",
    status: "Applied",
    comment: "",
  },
  {
    id: 18,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Senior Software Engineer - Full Stack (835093)",
    status: "Applied",
    comment: "",
  },
  {
    id: 19,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Senior Software Engineer (840037)",
    status: "Applied",
    comment: "",
  },
  {
    id: 20,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Software Engineer II (844133)",
    status: "Applied",
    comment: "",
  },
  {
    id: 21,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Software Engineer II (844131)",
    status: "Applied",
    comment: "",
  },
  {
    id: 22,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Software Engineer II (840598)",
    status: "Applied",
    comment: "",
  },
  {
    id: 23,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Software Engineer II (845839)",
    status: "Applied",
    comment: "",
  },
  {
    id: 24,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Software Engineer II (840016)",
    status: "Applied",
    comment: "",
  },
  {
    id: 25,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Software Engineer (849417)",
    status: "Applied",
    comment: "",
  },
  {
    id: 26,
    dateApplied: "2020-07-24",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Software Engineer (865584)",
    status: "Applied",
    comment: "",
  },
  {
    id: 27,
    dateApplied: "2020-08-10",
    location: { country: "Canada", state: "BC", city: "Vancouver" },
    company: "Microsoft",
    position: "Senior Software Engineer (869244)",
    status: "Failed",
    comment: "",
  },
  {
    id: 28,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "ON", city: "Waterloo" },
    company: "Google",
    position:
      "Senior Software Developer, Infrastructure, Google Cloud - Waterloo",
    status: "Applied",
    comment: "",
  },
  {
    id: 29,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "ON", city: "Waterloo" },
    company: "Google",
    position: "Software Developer, Cloud Health and Life Sciences - Waterloo",
    status: "Applied",
    comment: "",
  },
  {
    id: 30,
    dateApplied: "2020-06-30",
    location: { country: "Canada", state: "ON", city: "Waterloo" },
    company: "Google",
    position: "Software Developer",
    status: "Applied",
    comment: "",
  },
];

export function getApplications() {
  return applications;
}

export function getApplication(id) {
  return applications.find((a) => a.id === id);
}

export function saveApplicaiton(application) {
  let appInDb = applications.find((a) => a.id === applications.id) || {};
  appInDb.dateApplied = application.dateApplied;
  appInDb.Location = application.Location;
  appInDb.Company = application.Company;
  appInDb.Status = application.Status;
  appInDb.Comment = application.Comment;

  if (!appInDb.id) {
    applications.push(application);
  }
}
